### ISSUE TITLE
Link to paper is broken

### ISSUE THREAD

**Issue by ddssff** [AshleyYakeley/witness#1]
http://semantic.org/stuff/Open-Witnesses.pdf

**Comment by AshleyYakeley** [comment]
I've uploaded it to https://semantic.org/wp-content/uploads/Open-Witnesses.pdf

However, I'll probably delete the link in the documentation of the witness package, since the paper is not that relevant. It's more relevant to the open-witness package. It's from 2008 in any case, and a lot has changed since then.

**Comment by AshleyYakeley** [comment]
Link deleted.
